-- upgrade --
ALTER TABLE "cart" ADD "lat" DOUBLE PRECISION NOT NULL  DEFAULT 0;
ALTER TABLE "cart" ADD "lang" DOUBLE PRECISION NOT NULL  DEFAULT 0;
ALTER TABLE "cartsubs" DROP COLUMN "lat";
ALTER TABLE "cartsubs" DROP COLUMN "lang";
-- downgrade --
ALTER TABLE "cart" DROP COLUMN "lat";
ALTER TABLE "cart" DROP COLUMN "lang";
ALTER TABLE "cartsubs" ADD "lat" DOUBLE PRECISION NOT NULL  DEFAULT 0;
ALTER TABLE "cartsubs" ADD "lang" DOUBLE PRECISION NOT NULL  DEFAULT 0;
